gui:
  title: "&9&lɪɴғᴏ ᴅᴇʟ ᴄᴀᴠᴀʟʟᴏ"
  size: 27

items:
  info:
    slot: 13
    material: PAPER
    display_name: "&a&lᴛᴜᴛᴛᴇ ʟᴇ ɪɴғᴏʀᴍᴀᴢɪᴏɴɪ"
    lore:
      - "&f&m------------------------"
      - "&6✎ ɴᴏᴍᴇ: &e%HORSE_NAME%"
      - "&6🐴 ᴛɪᴘᴏ: &e%HORSE_TYPE%"
      - "&6🕒 ᴀᴅᴅᴏᴍᴇѕᴛɪᴄᴀᴛᴏ: &e%TAMED_DATE%"
      - "&6💨 ᴠᴇʟᴏᴄɪᴛà: &e%HORSE_SPEED%"
      - "&6🐎 ѕᴀʟᴛᴏ: &e%HORSE_JUMP%"
      - "&6❤ ᴄᴜᴏʀɪ: &e%HORSE_HEARTS%"
      - "&6🌟 ᴘᴜɴᴛᴇɢɢɪᴏ: &e%HORSE_SCORE%"
      - "&f&m------------------------"

  type:
    slot: 3
    material: LEATHER_HORSE_ARMOR
    display_name: "&6&l🐴 ᴛɪᴘᴏ ᴅɪ ᴄᴀᴠᴀʟʟᴏ"
    lore:
      - "&e%HORSE_TYPE%"

  name:
    slot: 4
    material: NAME_TAG
    display_name: "&b&l✎ ɴᴏᴍᴇ"
    lore:
      - "&e%HORSE_NAME%"

  date:
    slot: 5
    material: CLOCK
    display_name: "&6&l🕒 ᴅᴀᴛᴀ ᴅɪ ᴀᴅᴅᴏᴍᴇѕᴛɪᴄᴀᴍᴇɴᴛᴏ"
    lore:
      - "&e%TAMED_DATE%"

  speed:
    slot: 12
    material: SUGAR
    display_name: "&c&l💨 ᴠᴇʟᴏᴄɪᴛà"
    lore:
      - "&e%HORSE_SPEED%"

  jump:
    slot: 14
    material: RABBIT_FOOT
    display_name: "&a&l🐎 ѕᴀʟᴛᴏ"
    lore:
      - "&e%HORSE_JUMP%"

  hearts:
    slot: 22
    material: GOLDEN_APPLE
    display_name: "&d&l❤ ᴄᴜᴏʀɪ"
    lore:
      - "&e%HORSE_HEARTS%"

  score:
    slot: 26
    material: EMERALD
    display_name: "&e&l🌟 ᴘᴜɴᴛᴇɢɢɪᴏ"
    lore:
      - "&e%HORSE_SCORE%"
